### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by cbbjames** [ZhenYangIACAS/unsupervised-NMT#1]
Hi thanks for the great work!

Could you kindly add descriptions wherewith I can follow and run the codes?
How should I get the data and prepare them? How scripts are executed in order? 

Thanks in advance!

**Comment by ZhenYangIACAS** [comment]
@cbbjames  Hi, thanks for you liking our code. For the data, we used the publicly available wmt data, you can find the links in our paper to download these datasets. For running our code, you only need to make right configuration in the configure file and run the train_unsuper_en2de.sh. It is very easy.

**Comment by b03902128** [comment]
Thanks!

**Comment by cbbjames** [comment]
Thanks!
